
import pytest
from unittest.mock import patch
import pandas as pd
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.join(current_dir, '../..')
sys.path.append(project_root)

from analytics.etl_dim_analytics import transform_dimension_data

@patch('analytics.etl_dim_analytics.extract_dimension_data')
@patch('utils.db_utils.subrogate_key')
def test_extract_daily_data(mock_subrogate_key, mock_extract_dimension_data):
    
    mock_extract_dimension_data.return_value = pd.DataFrame({
        'Symbol': ['IBM'],
        'AssetType': ['Common Stock'],
        'Name': ['International Business Machines'],
        'Description': ['International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.'],
        'CIK': ['51143'],
        'Exchange': ['NYSE'],
        'Currency': ['USD'],
        'Country': ['USA'],
        'Sector': ['TECHNOLOGY'],
        'Industry': ['COMPUTER & OFFICE EQUIPMENT'],
        'Address': ['1 NEW ORCHARD ROAD, ARMONK, NY, US'],
        'OfficialSite': ['https://www.ibm.com'],
        'FiscalYearEnd': ['December'],
        'LatestQuarter': ['2024-06-30'],
        'MarketCapitalization': ['215244653000'],
        'EBITDA': ['14625000000'],
        'PERatio': ['25.79'],
        'PEGRatio': ['4.561'],
        'BookValue': ['26.08'],
        'DividendPerShare': ['6.65'],
        'DividendYield': ['0.0287'],
        'EPS': ['9.06'],
        'RevenuePerShareTTM': ['68.06'],
        'ProfitMargin': ['0.135'],
        'OperatingMarginTTM': ['0.149'],
        'ReturnOnAssetsTTM': ['0.047'],
        'ReturnOnEquityTTM': ['0.362'],
        'RevenueTTM': ['62363001000'],
        'GrossProfitTTM': ['32688000000'],
        'DilutedEPSTTM': ['9.06'],
        'QuarterlyEarningsGrowthYOY': ['0.141'],
        'QuarterlyRevenueGrowthYOY': ['0.019'],
        'AnalystTargetPrice': ['205.08'],
        'AnalystRatingStrongBuy': ['4'],
        'AnalystRatingBuy': ['5'],
        'AnalystRatingHold': ['10'],
        'AnalystRatingSell': ['3'],
        'AnalystRatingStrongSell': ['0'],
        'TrailingPE': ['25.79'],
        'ForwardPE': ['21.88'],
        'PriceToSalesRatioTTM': ['3.451'],
        'PriceToBookRatio': ['8.93'],
        'EVToRevenue': ['4.181'],
        'EVToEBITDA': ['17.23'],
        'Beta': ['0.697'],
        '52WeekHigh': ['237.37'],
        '52WeekLow': ['130.68'],
        '50DayMovingAverage': ['209.33'],
        '200DayMovingAverage': ['186.5'],
        'SharesOutstanding': ['921148000'],
        'DividendDate': ['2024-09-10'],
        'ExDividendDate': ['2024-08-09']
    })
    
    mock_subrogate_key.return_value = 'fake_key'
    
    result_df = transform_dimension_data()
        
    expected_columns = ['ticker', 'asset_type', 'name', 'country', 'sector', 'industry', 'address', 
        'official_site', 'analyst_rating', 'subrogate_key', 'is_current', 'audit_datetime']
       
    try:
        assert all(column in result_df.columns for column in expected_columns)

    except Exception as e:
        pytest.fail(f'Error al ejecutar extract_daily_data: {e}')

if __name__ == '__main__':
    pytest.main()
